/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ProjectsScorecardComponent } from "./ProjectsScorecard.component";

@NgModule({
  declarations: [ProjectsScorecardComponent],
  imports: [CommonModule],
  exports: [ProjectsScorecardComponent],
})
export class ProjectsScorecardModule {}
