/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-projects-scorecard",
  template: `
    <section
      class="flex relative flex-col flex-1 shrink justify-between px-8 pt-6 pb-16 bg-white rounded-lg basis-0 min-w-[240px] max-md:px-5 max-md:max-w-full"
    >
      <button
        class="flex absolute right-0 bottom-0 z-0 gap-1 items-center self-start px-7 py-3 h-10 text-sm font-semibold leading-tight text-blue-500 bg-blue-50 min-h-[40px] rounded-[40px_0px_8px_0px] max-md:px-5"
      >
        <span class="gap-2 self-stretch px-1 my-auto">See All Projects</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/08121c6d9e78764930a2c0467386963573349798e5fb39307b3b520a3f1a4616?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
          alt=""
          class="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
        />
      </button>
      <header class="flex z-0 justify-between items-start w-full">
        <h2
          class="flex flex-col flex-1 shrink items-start text-lg font-semibold leading-tight basis-0 min-w-[240px] text-gray-950"
        >
          <span class="gap-1.5 self-stretch">Projects By Scorecard Rating</span>
        </h2>
        <button class="flex gap-2 items-center w-6">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6dcb8207c26555a51aaba34600c2303d7510f81b30d93711b2136f8dcd92e8d4?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
            alt=""
            class="object-contain self-stretch my-auto w-6 aspect-square"
          />
        </button>
      </header>
      <div class="flex z-0 gap-2 justify-center items-start mt-6 w-full">
        <div
          class="flex flex-col items-end py-px text-xs leading-tight whitespace-nowrap text-zinc-600 max-md:hidden"
        >
          <div>20</div>
          <div class="mt-2">18</div>
          <div class="mt-2">16</div>
          <div class="mt-2">14</div>
          <div class="mt-2">12</div>
          <div class="mt-2">10</div>
          <div class="mt-2">8</div>
          <div class="mt-2">6</div>
          <div class="mt-2">4</div>
          <div class="mt-2">2</div>
        </div>
        <div class="flex flex-col flex-1 shrink basis-0 min-w-[240px]">
          <div class="flex gap-1 items-end w-full">
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-red-300 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-orange-200 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
            </div>
            <div class="flex flex-col flex-1 shrink basis-0">
              <div class="flex w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
              <div class="flex mt-1 w-full bg-emerald-200 min-h-[16px]"></div>
            </div>
          </div>
          <div
            class="flex gap-5 justify-between items-center px-2 mt-2 w-full text-xs leading-tight whitespace-nowrap text-gray-950"
          >
            <div class="self-stretch my-auto">0</div>
            <div class="self-stretch my-auto">1</div>
            <div class="self-stretch my-auto">2</div>
            <div class="self-stretch my-auto">3</div>
            <div class="self-stretch my-auto">4</div>
            <div class="self-stretch my-auto">5</div>
            <div class="self-stretch my-auto">6</div>
            <div class="self-stretch my-auto">7</div>
            <div class="self-stretch my-auto">8</div>
            <div class="self-stretch my-auto">9</div>
            <div class="self-stretch my-auto">10</div>
          </div>
        </div>
      </div>
    </section>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class ProjectsScorecardComponent {}
