/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { MyAccountComponent } from "./MyAccount.component";

@NgModule({
  declarations: [MyAccountComponent],
  imports: [CommonModule],
  exports: [MyAccountComponent],
})
export class MyAccountModule {}
