/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-my-account",
  template: `
    <main
      class="flex flex-col px-8 py-6 w-full bg-white rounded-lg max-md:px-5 max-md:max-w-full"
    >
      <header
        class="flex flex-wrap justify-between items-start w-full max-md:max-w-full"
      >
        <h1
          class="flex flex-col flex-1 shrink items-start text-2xl font-bold leading-tight basis-0 min-w-[240px] text-gray-950 max-md:max-w-full"
        >
          My Account
        </h1>
        <button class="flex gap-2 items-center w-6" aria-label="Settings">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/68db75247fb1cd5c4ec5288e7328c0168e616d92426db1c8497e78c1f62cab14?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
            alt=""
            class="object-contain self-stretch my-auto w-6 aspect-square"
          />
        </button>
      </header>
      <section class="flex flex-wrap gap-5 mt-6 w-full max-md:max-w-full">
        <div
          class="flex flex-1 shrink gap-4 h-full basis-0 min-w-[240px] max-md:max-w-full"
        >
          <div class="flex relative flex-col self-start w-[104px]">
            <button
              class="flex absolute top-0 right-0 z-0 gap-2 items-center p-1 w-6 rounded"
              aria-label="Edit profile picture"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d6c9dce01f09983b794177a21b04bc7db04e5760b2f10e7297dc008eea4101d8?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
                alt=""
                class="object-contain self-stretch my-auto w-4 aspect-square"
              />
            </button>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/072f4ad4ee0be33007867b962183c127861ad8062cabceb1154496f960990903?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
              alt="Jonathan Anderson's profile picture"
              class="object-contain z-0 self-center max-w-full aspect-square w-[104px]"
            />
          </div>
          <div class="flex flex-col justify-between text-sm leading-tight">
            <div class="flex flex-col self-start text-gray-950">
              <h2 class="font-semibold">Jonathan Anderson</h2>
              <p class="mt-1">Sr. Engineer at Pinterest</p>
              <p class="mt-1">+1 (234) 567 8901</p>
              <address class="mt-1 leading-4 not-italic">
                123 Main Street New York, NY 00890, USA
              </address>
            </div>
            <div class="flex flex-col mt-11 max-md:mt-10">
              <div class="flex gap-1 items-start whitespace-nowrap">
                <span class="text-gray-950">Username:</span>
                <span class="text-neutral-400">jonathananderson</span>
              </div>
              <button class="gap-1 self-start mt-1 text-blue-500 rounded">
                Change Password
              </button>
            </div>
          </div>
        </div>
        <div
          class="flex flex-col flex-1 shrink items-start self-start leading-tight basis-0 min-w-[240px] max-md:max-w-full"
        >
          <div class="flex flex-col items-start">
            <div
              class="flex gap-1 items-start text-sm whitespace-nowrap text-gray-950"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/167a4d6f004990880ae1a7c3f195ad7cfe615cc2ee1142f4ed11e3e061245d26?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
                alt=""
                class="object-contain shrink-0 w-4 aspect-square"
              />
              <span>jonathananderson</span>
            </div>
            <div class="flex gap-1 items-start self-stretch mt-1">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c4a5a4e0606a2c0d373f8471ee271a8ac02ddc94b129f4a95904372dccc90d67?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
                alt=""
                class="object-contain shrink-0 w-4 aspect-square"
              />
              <span class="text-sm text-gray-950">janderson.com</span>
              <span class="text-xs text-neutral-400"
                >Primary Email, Meeting Invitations</span
              >
            </div>
            <div
              class="flex gap-1 items-start mt-1 text-sm whitespace-nowrap text-gray-950"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c4a5a4e0606a2c0d373f8471ee271a8ac02ddc94b129f4a95904372dccc90d67?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
                alt=""
                class="object-contain shrink-0 w-4 aspect-square"
              />
              <span>jonathananderson.com</span>
            </div>
            <div
              class="flex gap-1 items-start mt-1 text-sm whitespace-nowrap text-gray-950"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/96507296a434bc10582d9546948635a673d803a4bc871dd0d75f0f09320d3390?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
                alt=""
                class="object-contain shrink-0 w-4 aspect-square"
              />
              <span>jonathananderson.com</span>
            </div>
            <button
              class="gap-1 self-stretch px-4 mt-1 text-sm font-semibold text-blue-500 bg-blue-50 rounded-lg min-h-[32px]"
            >
              Add an Account
            </button>
          </div>
          <div class="flex flex-col mt-6 text-sm text-blue-500">
            <button class="gap-1 self-start rounded">
              Manage Email Settings
            </button>
            <button class="mt-1">Purchase Linux.com Email</button>
          </div>
        </div>
      </section>
    </main>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class MyAccountComponent {}
