/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { CardModule } from "primeng/card";
import { InputSwitchModule } from "primeng/inputswitch";
import { ButtonModule } from "primeng/button";
import { PrivacySettingsComponent } from "./privacy-settings.component";

@NgModule({
  declarations: [PrivacySettingsComponent],
  imports: [
    CommonModule,
    FormsModule,
    CardModule,
    InputSwitchModule,
    ButtonModule,
  ],
  exports: [PrivacySettingsComponent],
})
export class PrivacySettingsModule {}
