/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-work-history",
  standalone: true,
  imports: [CommonModule],
  template: `
    <section
      class="flex flex-col justify-center items-center px-8 py-6 mt-6 w-full font-semibold leading-tight bg-white rounded-lg max-md:px-5 max-md:max-w-full"
    >
      <header
        class="flex flex-wrap gap-5 justify-between items-start self-stretch w-full max-md:max-w-full"
      >
        <h2 class="text-lg text-gray-950">My Work History</h2>
        <button
          class="gap-1 self-stretch px-4 text-sm text-blue-500 bg-blue-50 rounded-lg min-h-[32px]"
          aria-label="Add Position"
        >
          Add Position
        </button>
      </header>
      <p class="mt-6 text-sm text-gray-950">
        You have no work history entered.
      </p>
      <button
        class="flex gap-1 items-center px-7 py-3 mt-6 text-sm text-white bg-amber-400 rounded-lg min-h-[40px] max-md:px-5"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6a96d617c3fb5de9cbb0d6c82c16239138092458ba5cc54777335f64ecbde8f5?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
          class="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
          alt=""
        />
        <span class="gap-2 self-stretch px-1 my-auto">Sync with LinkedIn</span>
      </button>
    </section>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class WorkHistoryComponent {}
