/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-organizational-contributors",
  template: `
    <section
      class="flex flex-col flex-1 shrink justify-center basis-0 min-w-[240px]"
    >
      <h2 class="gap-4 self-stretch w-full text-gray-950">
        Organizational Contributors
      </h2>
      <div
        class="flex gap-2 items-start mt-4 w-full text-xs whitespace-nowrap text-neutral-400"
      >
        <div class="flex shrink-0 w-12 h-[207px]"></div>
        <div class="flex flex-col justify-between items-end pb-2 min-h-[208px]">
          <div class="flex gap-0.5 items-center">
            <span class="self-stretch my-auto">30%</span>
            <div
              class="shrink-0 self-stretch my-auto w-1 h-px border border-solid border-neutral-400"
            ></div>
          </div>
          <div class="flex gap-0.5 items-center mt-8">
            <span class="self-stretch my-auto">20%</span>
            <div
              class="shrink-0 self-stretch my-auto w-1 h-px border border-solid border-neutral-400"
            ></div>
          </div>
          <div class="flex gap-0.5 items-center mt-8">
            <span class="self-stretch my-auto">10%</span>
            <div
              class="shrink-0 self-stretch my-auto w-1 h-px border border-solid border-neutral-400"
            ></div>
          </div>
          <div class="flex gap-0.5 items-center mt-8">
            <span class="self-stretch my-auto">0%</span>
            <div
              class="shrink-0 self-stretch my-auto w-1 h-px border border-solid border-neutral-400"
            ></div>
          </div>
          <div class="flex gap-0.5 items-center mt-8">
            <span class="self-stretch my-auto">-10%</span>
            <div
              class="shrink-0 self-stretch my-auto w-1 h-px border border-solid border-neutral-400"
            ></div>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/1d817d54f3bdc9da91edecec05ea7ca5fe9a1e832091f052c283d09b2c5cb05a?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
          alt="Graph of organizational contributors"
          class="object-contain flex-1 shrink self-stretch aspect-[0.95] basis-0 w-[197px]"
        />
      </div>
      <div
        class="flex justify-between items-center mt-4 w-full text-xs whitespace-nowrap"
      >
        <div
          class="flex flex-col items-start self-stretch my-auto w-20 text-blue-500"
        >
          <div class="flex gap-1 items-center">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e68ef380d4dc04c37d2be139b82bad0f869ee6a1257d51b0ee3460946a3c47fa?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
              alt=""
              class="object-contain shrink-0 self-stretch my-auto w-2 aspect-square"
            />
            <span class="gap-1 self-stretch my-auto rounded">Containerd</span>
          </div>
          <div class="flex gap-1 items-center mt-3">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/82b4f9c593f8aaea18761c223a4433d6eaf5893e61d890a7a22940b9349fcba1?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
              alt=""
              class="object-contain shrink-0 self-stretch my-auto w-2 aspect-square"
            />
            <span class="gap-1 self-stretch my-auto rounded">Dapr</span>
          </div>
          <div class="flex gap-1 items-center mt-3">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/299df0c4e92ec726bb2c2812cea56d3c15202e55ad117a62ab3f8442a9969c7f?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
              alt=""
              class="object-contain shrink-0 self-stretch my-auto w-2 aspect-square"
            />
            <span class="gap-1 self-stretch my-auto rounded">Envoy</span>
          </div>
          <div class="flex gap-1 items-center mt-3">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3caef945920edf7bd533e311abed8b0625b7703e83f16cd976226598558f42d1?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
              alt=""
              class="object-contain shrink-0 self-stretch my-auto w-2 aspect-square"
            />
            <span class="gap-1 self-stretch my-auto rounded">gPRC</span>
          </div>
          <div class="flex gap-1 items-center mt-3">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8a83813c028e0d9e765e15156478bc62deea564a46edb97034491f203cf8e324?apiKey=fb7a9e10776d4e8394e84cfd90993eb3&&apiKey=fb7a9e10776d4e8394e84cfd90993eb3"
              alt=""
              class="object-contain shrink-0 self-stretch my-auto w-2 aspect-square"
            />
            <span class="gap-1 self-stretch my-auto rounded">Strimzi</span>
          </div>
        </div>
        <div
          class="flex flex-1 shrink gap-5 items-center self-stretch pr-6 pl-10 my-auto text-right basis-0 text-gray-950 max-md:px-5"
        >
          <div
            class="flex flex-col flex-1 shrink items-end self-stretch my-auto basis-0"
          >
            <span>40</span>
            <span class="mt-3">30</span>
            <span class="mt-3">50</span>
            <span class="mt-3">10</span>
            <span class="mt-3">35</span>
          </div>
          <div
            class="flex flex-col flex-1 shrink items-end self-stretch my-auto basis-0"
          >
            <span>44</span>
            <span class="mt-3">36</span>
            <span class="mt-3">53</span>
            <span class="mt-3">11</span>
            <span class="mt-3">31</span>
          </div>
          <div
            class="flex flex-col flex-1 shrink items-end self-stretch my-auto basis-0"
          >
            <span>50</span>
            <span class="mt-3">42</span>
            <span class="mt-3">58</span>
            <span class="mt-3">13</span>
            <span class="mt-3">35</span>
          </div>
          <div
            class="flex flex-col flex-1 shrink items-end self-stretch my-auto basis-0"
          >
            <span>60</span>
            <span class="mt-3">44</span>
            <span class="mt-3">65</span>
            <span class="mt-3">13</span>
            <span class="mt-3">45</span>
          </div>
        </div>
      </div>
      <button
        class="gap-1 self-end px-3 mt-4 text-blue-500 bg-blue-50 rounded-lg min-h-[28px]"
      >
        Explore More
      </button>
    </section>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class OrganizationalContributorsComponent {}
