/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { OrganizationalContributorsComponent } from "./organizational-contributors.component";

@NgModule({
  declarations: [OrganizationalContributorsComponent],
  imports: [CommonModule],
  exports: [OrganizationalContributorsComponent],
})
export class OrganizationalContributorsModule {}
